[package]

name = "conrod"
version = "0.0.0"
authors = ["Mitchell Nordine <mitchell.nordine@gmail.com>"]

[[lib]]

name = "conrod"
path = "./src/lib.rs"

[dependencies.piston]

git = "https://github.com/PistonDevelopers/piston"

[dependencies.graphics]

git = "https://github.com/PistonDevelopers/rust-graphics.git"

[dependencies.opengl_graphics]

git = "https://github.com/PistonDevelopers/opengl_graphics.git"

