[package]
name = "conrod"
version = "0.37.2"
authors = [
    "Mitchell Nordine <mitchell.nordine@gmail.com>",
    "Sven Nilsen <bvssvni@gmail.com>"
]
keywords = ["ui", "widgets", "gui", "piston", "graphics"]
description = "An easy-to-use, extensible 2D GUI library"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/pistondevelopers/conrod.git"
homepage = "https://github.com/pistondevelopers/conrod"
documentation = "http://docs.piston.rs/conrod/conrod/"

[lib]
name = "conrod"
path = "./src/lib.rs"

[dependencies]
daggy = "0.4.0"
num = "0.1.30"
pistoncore-input = "0.13.0"
rusttype = "0.2.0"

# Feature-gated dependencies.
glium = { version = "0.15.0", optional = true }
glutin = { version = "0.6.1", optional = true }
piston2d-graphics = { version = "0.16.0", optional = true }

[features]
piston = ["draw_piston", "event_piston"]
draw_glium = ["glium"]
draw_piston = ["piston2d-graphics"]
event_glutin = ["glutin"]
event_piston = []

[dev-dependencies]
find_folder = "0.3.0"
rand = "0.3.13"
piston_window = "0.50.0"
