[package]

name = "conrod"
version = "0.7.2"
authors = [
    "Mitchell Nordine <mitchell.nordine@gmail.com>",
    "Sven Nilsen <bvssvni@gmail.com>"
]
keywords = ["ui", "widgets", "immediate-mode", "piston"]
description = "An easy-to-use, immediate-mode, 2D GUI library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/conrod.git"
homepage = "https://github.com/pistondevelopers/conrod"


[lib]

name = "conrod"
path = "./src/lib.rs"


[dependencies]
bitflags = "*"
clock_ticks = "0.0.6"
elmesque = "0.3.0"
json_io = "0.1.2"
petgraph = "0.1.10"
pistoncore-input = "0.3.0"
piston2d-graphics = "0.4.0"
num = "*"
rand = "*"
rustc-serialize = "*"
vecmath = "0.1.1"

[dev-dependencies]
find_folder = "0.2.0"
gfx = "0.6.5"
gfx_device_gl = "0.4.1"
piston-viewport = "0.1.0"
piston_window = "0.11.0"
piston2d-gfx_graphics = "0.4.0"
piston2d-opengl_graphics = "0.6.0"
pistoncore-glutin_window = "0.7.0"
piston = "0.5.0"
