[package]

name = "conrod"
version = "0.23.0"
authors = [
    "Mitchell Nordine <mitchell.nordine@gmail.com>",
    "Sven Nilsen <bvssvni@gmail.com>"
]
keywords = ["ui", "widgets", "immediate-mode", "piston"]
description = "An easy-to-use, immediate-mode, 2D GUI library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/conrod.git"
homepage = "https://github.com/pistondevelopers/conrod"
documentation = "http://docs.piston.rs/conrod/conrod/"


[lib]

name = "conrod"
path = "./src/lib.rs"


[dependencies]
time = "0.1.34"
daggy = "0.3.0"
pistoncore-input = "0.8.0"
piston2d-graphics = "0.12.0"
num = "0.1.27"
rand = "0.3.12"
vecmath = "0.2.0"

[dev-dependencies]
find_folder = "0.3.0"
gfx = "0.8.1"
piston-viewport = "0.2.0"
piston_window = "0.32.0"
piston2d-gfx_graphics = "0.16.0"
piston2d-opengl_graphics = "0.21.0"
pistoncore-glutin_window = "0.20.0"
piston = "0.16.0"

