[package]

name = "conrod"
version = "0.1.2"
authors = [
    "Mitchell Nordine <mitchell.nordine@gmail.com>",
    "Sven Nilsen <bvssvni@gmail.com>"
]
keywords = ["ui", "widgets", "immediate-mode", "piston"]
description = "An easy-to-use, immediate-mode, 2D GUI library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/conrod.git"
homepage = "https://github.com/pistondevelopers/conrod"


[lib]

name = "conrod"
path = "./src/lib.rs"


[dependencies]
bitflags = "*"
clock_ticks = "0.0.6"
elmesque = "0.1.0"
piston = "0.1.3"
piston2d-graphics = "0.0.48"
num = "*"
rand = "*"
rustc-serialize = "*"
vecmath = "0.0.23"

[dev-dependencies]
gfx = "0.6.*"
gfx_device_gl = "0.4.*"
piston-viewport = "0.0.3"
piston_window = "0.0.8"
piston2d-gfx_graphics = "0.1.21"
piston2d-opengl_graphics = "0.0.17"
pistoncore-glutin_window = "0.0.9"

