[package]

name = "conrod"
version = "0.0.0"
authors = [
    "Mitchell Nordine <mitchell.nordine@gmail.com>",
    "Sven Nilsen <bvssvni@gmail.com>"
]

[lib]

name = "conrod"
path = "./src/lib.rs"

[dependencies.pistoncore-input]

git = "https://github.com/PistonDevelopers/input/"

[dependencies.pistoncore-event]

git = "https://github.com/PistonDevelopers/event"

[dependencies.piston2d-graphics]

git = "https://github.com/PistonDevelopers/graphics.git"

[dependencies.piston2d-opengl_graphics]

git = "https://github.com/PistonDevelopers/opengl_graphics.git"

[dependencies.freetype-rs]

git = "https://github.com/PistonDevelopers/freetype-rs.git"

[dependencies.quack]

git = "https://github.com/PistonDevelopers/quack"

[dependencies.rustc-serialize]

version = "*"

[dependencies.vecmath]

git = "https://github.com/PistonDevelopers/vecmath.git"

[dev-dependencies.pistoncore-sdl2_window]

git = "https://github.com/PistonDevelopers/sdl2_window.git"

[dev-dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"

[dependencies]
time = "*"
bitflags = "0.1"
