[workspace]
members = [
    "conrod_core",
    "conrod_derive",
    "backends/conrod_example_shared",
    "backends/conrod_winit",
    "backends/conrod_glium",
    "backends/conrod_gfx",
    "backends/conrod_piston",
]
